#pragma once

/*
 * board_config.h for esp32c3-devkitc
 * Generated by duneos-bspgen on 2026-05-11 10:59 UTC
 * DO NOT EDIT — re-generate from boards/esp32c3-devkitc.yaml
 */

#define DUNEOS_BOARD_NAME                        "esp32c3-devkitc"
#define DUNEOS_CPU_ESP32C3                       1
#define DUNEOS_CPU_ARCH                          "riscv"
#define DUNEOS_ELF_MACHINE                       EM_RISCV
#define DUNEOS_FLASH_SIZE_MB                     4
#define DUNEOS_PSRAM_SIZE_MB                     0

/* ---------- UART0 ---------- */
#define DUNEOS_UART0_TX_PIN                      21
#define DUNEOS_UART0_RX_PIN                      20
#define DUNEOS_UART0_BAUD                        115200

/* ---------- SPI SD card ---------- */
#define DUNEOS_SD_SPI_HOST                       SPI2_HOST
#define DUNEOS_SD_MOSI_PIN                       6
#define DUNEOS_SD_MISO_PIN                       2
#define DUNEOS_SD_CLK_PIN                        4
#define DUNEOS_SD_CS_PIN                         10
#define DUNEOS_SD_FREQ_KHZ                       20000
#define DUNEOS_SD_CD_PIN                         -1

/* ---------- LED status ---------- */
#define DUNEOS_LED_STATUS_PIN                    8
#define DUNEOS_LED_STATUS_ACTIVE_HIGH            1

