#pragma once

/*
 * board_config.h for lilygo-t-embed-cc1101
 * Generated by duneos-bspgen from boards/lilygo-t-embed-cc1101.yaml
 * DO NOT EDIT — re-generate with:
 *   python tools/duneos-bspgen.py boards/lilygo-t-embed-cc1101.yaml
 *
 * Pin assignments from LilyGo T-Embed-CC1101 reference firmware.
 */

#define DUNEOS_BOARD_NAME                        "lilygo-t-embed-cc1101"
#define DUNEOS_CPU_ESP32S3                       1
#define DUNEOS_CPU_ARCH                          "xtensa"
#define DUNEOS_ELF_MACHINE                       EM_XTENSA
#define DUNEOS_FLASH_SIZE_MB                     16
#define DUNEOS_PSRAM_SIZE_MB                     8

/* ---------- UART0 ---------- */
#define DUNEOS_UART0_TX_PIN     43
#define DUNEOS_UART0_RX_PIN     44
#define DUNEOS_UART0_BAUD       115200

/* ---------- SPI2 (shared: SD card, ST7789 display, CC1101) ---------- */
#define DUNEOS_SD_SPI_HOST      SPI2_HOST
#define DUNEOS_SD_MOSI_PIN      9
#define DUNEOS_SD_MISO_PIN      10
#define DUNEOS_SD_CLK_PIN       11
#define DUNEOS_SD_CS_PIN        13
#define DUNEOS_SD_FREQ_KHZ      40000
#define DUNEOS_SD_CD_PIN        (-1)

/* ---------- I2C0 (BQ25896 charger + BQ27220 fuel gauge + PN532 NFC) ---------- */
#define DUNEOS_HAVE_I2C         1
#define DUNEOS_I2C0_SDA_PIN     8
#define DUNEOS_I2C0_SCL_PIN     18
#define DUNEOS_I2C0_FREQ_HZ     100000

/* ---------- Display (ST7789, 240x280, shared SPI2 bus) ---------- */
#define DUNEOS_DISPLAY_WIDTH    240
#define DUNEOS_DISPLAY_HEIGHT   280
#define DUNEOS_DISPLAY_SPI_HOST SPI2_HOST
#define DUNEOS_DISPLAY_MOSI_PIN 9
#define DUNEOS_DISPLAY_CLK_PIN  11
#define DUNEOS_DISPLAY_CS_PIN   41
#define DUNEOS_DISPLAY_DC_PIN   16
#define DUNEOS_DISPLAY_RST_PIN  40
#define DUNEOS_DISPLAY_BL_PIN   21
#define DUNEOS_DISPLAY_FREQ_HZ  40000000

/* ---------- Battery (BQ27220 fuel gauge + BQ25896 charger) ---------- */
/* BQ27220 reports voltage/SoC/charging status via I2C registers.         */
/* BQ25896 charger status readable via DUNEOS_BATTERY_CHARGER_ADDR if     */
/* needed in the future (currently unused by the adc_simple backend).     */
#define DUNEOS_HAVE_BATTERY              1
#define DUNEOS_BATTERY_TYPE_BQ27220      1
#define DUNEOS_BATTERY_GAUGE_ADDR        0x55
#define DUNEOS_BATTERY_CHARGER_ADDR      0x6B

/* ---------- Power switch (CC1101 + WS2812 power rail) ---------- */
/* GPIO_NUM_15 — drive HIGH to power on CC1101 and onboard WS2812.        */

/* ---------- PN532 NFC (on I2C0) --------------------------------- */
/* IRQ=17  RESET=45                                                        */

/* ---------- SPI raw bus (/dev/spi-1) — shared with SD on SPI2 ---------- */
/* DUNEOS_SPI1_BUS_SHARED: bus already initialised by vfs.c SD mount.      */
/* Apps set their own CS via ioctl(SPI_SET_CS). CC1101 CS=GPIO14 GDO0=2.  */
#define DUNEOS_HAVE_SPI             1
#define DUNEOS_SPI1_HOST            SPI2_HOST
#define DUNEOS_SPI1_MOSI_PIN        9
#define DUNEOS_SPI1_MISO_PIN        10
#define DUNEOS_SPI1_CLK_PIN         11
#define DUNEOS_SPI1_MAX_FREQ_HZ     40000000
#define DUNEOS_SPI1_BUS_SHARED      1

/* ---------- GPIO buttons (KNOB_BTN + side KEY_BTN) ---------- */
#define DUNEOS_HAVE_BTN_GPIO        1
#define DUNEOS_BTN_GPIO_COUNT       2
#define DUNEOS_BTN_GPIO_PINS        {0, 6}
#define DUNEOS_BTN_GPIO_CODES       {0x0d, 0x1b}   /* KEY_ENTER, KEY_ESC */

/* ---------- Rotary encoder (quadrature, KNOB_A/B) ---------- */
#define DUNEOS_HAVE_ENCODER         1
#define DUNEOS_ENCODER_A_PIN        4
#define DUNEOS_ENCODER_B_PIN        5

/* ---------- Onboard WS2812 LED ---------- */
#define DUNEOS_LED_STATUS_PIN   48
#define DUNEOS_LED_ACTIVE_HIGH  1
#define DUNEOS_LED_STATUS_WS2812 1
