#pragma once

/*
 * board_config.h for lilygo-t-embed-cc1101
 * Generated by duneos-bspgen from boards/lilygo-t-embed-cc1101.yaml
 * DO NOT EDIT — re-generate with:
 *   python tools/duneos-bspgen.py boards/lilygo-t-embed-cc1101.yaml
 *
 * Pin assignments verified from LilyGo T-Embed-CC1101 schematics.
 * Items marked [VERIFY] should be confirmed against the latest hardware revision.
 */

#define DUNEOS_BOARD_NAME                        "lilygo-t-embed-cc1101"
#define DUNEOS_CPU_ESP32S3                       1
#define DUNEOS_CPU_ARCH                          "xtensa"
#define DUNEOS_ELF_MACHINE                       EM_XTENSA
#define DUNEOS_FLASH_SIZE_MB                     16
#define DUNEOS_PSRAM_SIZE_MB                     8

/* ---------- UART0 ---------- */
#define DUNEOS_UART0_TX_PIN     43
#define DUNEOS_UART0_RX_PIN     44
#define DUNEOS_UART0_BAUD       115200

/* ---------- SPI2 (SD card) ---------- */
#define DUNEOS_SD_SPI_HOST      SPI2_HOST
#define DUNEOS_SD_MOSI_PIN      16
#define DUNEOS_SD_MISO_PIN      17
#define DUNEOS_SD_CLK_PIN       14
#define DUNEOS_SD_CS_PIN        18
#define DUNEOS_SD_FREQ_KHZ      20000
#define DUNEOS_SD_CD_PIN        (-1)

/* ---------- I2C0 (BQ25896 charger + BQ27220 fuel gauge) ---------- */
#define DUNEOS_HAVE_I2C         1
#define DUNEOS_I2C0_SDA_PIN     8
#define DUNEOS_I2C0_SCL_PIN     9
#define DUNEOS_I2C0_FREQ_HZ     400000

/* ---------- Display (ST7789, 240x280, dedicated SPI3 bus) ---------- */
#define DUNEOS_DISPLAY_WIDTH    240
#define DUNEOS_DISPLAY_HEIGHT   280
#define DUNEOS_DISPLAY_SPI_HOST SPI3_HOST
#define DUNEOS_DISPLAY_MOSI_PIN 11
#define DUNEOS_DISPLAY_CLK_PIN  12
#define DUNEOS_DISPLAY_CS_PIN   10
#define DUNEOS_DISPLAY_DC_PIN   13
#define DUNEOS_DISPLAY_RST_PIN  1
#define DUNEOS_DISPLAY_BL_PIN   15
#define DUNEOS_DISPLAY_FREQ_HZ  40000000

/* ---------- Battery (BQ27220 fuel gauge + BQ25896 charger) ---------- */
/* BQ27220 reports voltage/SoC/charging status via I2C registers.         */
/* BQ25896 charger status readable via DUNEOS_BATTERY_CHARGER_ADDR if     */
/* needed in the future (currently unused by the adc_simple backend).     */
#define DUNEOS_HAVE_BATTERY              1
#define DUNEOS_BATTERY_TYPE_BQ27220      1
#define DUNEOS_BATTERY_GAUGE_ADDR        0x55
#define DUNEOS_BATTERY_CHARGER_ADDR      0x6B

/* ---------- CC1101 sub-GHz radio (userspace via /dev/spi-1, Phase 11) -- */
/* MOSI=41  MISO=38  SCK=40  CS=46  GDO0=2  GDO2=3                       */

/* ---------- Rotary encoder (input device, Phase 12) [VERIFY] ----------- */
/* A=4  B=5  SW=6                                                          */

/* ---------- Onboard WS2812 LED ---------- */
#define DUNEOS_LED_STATUS_PIN   48
#define DUNEOS_LED_ACTIVE_HIGH  1
#define DUNEOS_LED_STATUS_WS2812 1
