"""
boardgen — generate per-app `_board.h` from the active board.yaml + the app's
declared capabilities.

The header lands in `<app_build_dir>/_board.h` and is exposed to the app via
`-I<app_build_dir>` plus the alias header `kernel/duneos_kernel/include/duneos/
board.h` which simply does `#include "_board.h"`. App code writes:

    #include <duneos/board.h>
    int fd = open(DUNEOS_DISPLAY_DEV, O_WRONLY);

Moving the chip to a different bus (e.g. exposing SPI3 as /dev/spi-2 once
Phase 24.6 lands) means `DUNEOS_DISPLAY_DEV` changes value at build time; the
app source and SDK libs (libdisp.c, libgfx.c, …) keep working untouched.

This is ADR 015 Pattern 2.
"""

from __future__ import annotations

from pathlib import Path


def _flatten(board_cfg: dict) -> dict:
    """Return the board YAML's payload — either the top dict, or its `board:`
    sub-section if the file uses that nesting."""
    if "board" in board_cfg and isinstance(board_cfg["board"], dict):
        merged = {**board_cfg.get("board", {})}
        for k, v in board_cfg.items():
            if k != "board" and k not in merged:
                merged[k] = v
        return merged
    return board_cfg


def _display_block(board: dict, lines: list[str]) -> None:
    """Emit display-related defines.

    The kernel runs `/dev/disp0` (streaming ST7789) on non-PSRAM boards and
    `/dev/fb0` (PSRAM framebuffer) on PSRAM boards. Phase 24.6 will eventually
    expose SPI3 as `/dev/spi-2` for true userspace display drivers; until
    then, `DUNEOS_DISPLAY_DEV` always resolves to one of the two kernel paths.
    """
    disp = board.get("display")
    if not isinstance(disp, dict):
        return
    psram = int(board.get("psram_size_mb", 0) or 0)
    lines.append("/* ----- display ----- */")
    if psram > 0:
        lines.append('#define DUNEOS_DISPLAY_DEV       "/dev/fb0"')
    else:
        lines.append('#define DUNEOS_DISPLAY_DEV       "/dev/disp0"')
    if "driver" in disp:
        lines.append(f'#define DUNEOS_DISPLAY_DRIVER    "{disp["driver"]}"')
    if "width" in disp:
        lines.append(f"#define DUNEOS_DISPLAY_WIDTH     {int(disp['width'])}")
    if "height" in disp:
        lines.append(f"#define DUNEOS_DISPLAY_HEIGHT    {int(disp['height'])}")
    lines.append("")


def _input_block(board: dict, lines: list[str]) -> None:
    if board.get("keyboard_matrix") or board.get("buttons") or board.get("encoder"):
        lines.append("/* ----- input ----- */")
        lines.append('#define DUNEOS_INPUT_DEV         "/dev/input/event0"')
        lines.append("")


def _i2c_block(board: dict, lines: list[str]) -> None:
    i2c = board.get("i2c")
    if not i2c:
        return
    lines.append("/* ----- i2c ----- */")
    # board.yaml schema: i2c: [{id: 0, ...}, ...] OR i2c: {id: 0, ...}
    if isinstance(i2c, list):
        for bus in i2c:
            if isinstance(bus, dict) and "id" in bus:
                lines.append(f'#define DUNEOS_I2C{bus["id"]}_DEV         "/dev/i2c-{bus["id"]}"')
    elif isinstance(i2c, dict) and "id" in i2c:
        lines.append(f'#define DUNEOS_I2C{i2c["id"]}_DEV         "/dev/i2c-{i2c["id"]}"')
    # Convenience: alias I2C0 if a bus 0 exists (most common case).
    lines.append("")


def _storage_block(board: dict, lines: list[str]) -> None:
    has_sd = bool(board.get("sd_card"))
    lines.append("/* ----- storage ----- */")
    lines.append(f"#define DUNEOS_HAS_SD            {1 if has_sd else 0}")
    lines.append('#define DUNEOS_FLASH_MOUNT       "/flash"')
    lines.append('#define DUNEOS_SD_MOUNT          "/sd"')
    lines.append("")


def generate(board_cfg: dict, board_name: str, capabilities: list[str]) -> str:
    """Render the `_board.h` content for an app on `board_name`.

    Currently capabilities don't influence the emitted defines — every section
    is always written. Once the file grows, we can prune sections based on
    declared capabilities to keep the header small.
    """
    _ = capabilities   # reserved for future filtering
    b = _flatten(board_cfg)
    lines: list[str] = [
        "/* DuneOS — auto-generated by dbt for app build. DO NOT EDIT. */",
        f"/* Board: {board_name} */",
        "",
        "#pragma once",
        "",
        f'#define DUNEOS_BOARD_NAME        "{board_name}"',
        "",
    ]
    _storage_block(b, lines)
    _display_block(b, lines)
    _input_block(b, lines)
    _i2c_block(b, lines)
    return "\n".join(lines)


def write_to(build_dir: Path, board_cfg: dict, board_name: str,
             capabilities: list[str]) -> Path:
    build_dir.mkdir(parents=True, exist_ok=True)
    out = build_dir / "_board.h"
    out.write_text(generate(board_cfg, board_name, capabilities))
    return out
