/*
 * libst7789 — ST7789 userspace display library for DuneOS.
 *
 * Talks to the kernel-owned SPI and GPIO buses through their public ioctl
 * interfaces (/dev/spi-N, /dev/gpiochip0). Contains NO ESP-IDF or FreeRTOS
 * dependencies — pure-C userspace, usable from any DuneOS arch.
 *
 * Configuration is pulled from <duneos/board.h>, generated by dbt per
 * active board. The library never #includes board_config.h.
 *
 * This library implements `duneos_disp_ops` (see <duneos/disp.h>). Apps
 * link libdisp.c + libst7789.c via the `display` capability in their
 * manifest; the dispatch happens through the vtable.
 */

#include "duneos/disp.h"
#include "duneos/spi_ioctl.h"
#include "duneos/gpio_ioctl.h"
#include "duneos/board.h"     /* DUNEOS_DISPLAY_* — auto-generated by dbt */

#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>

/* PicoLibc hides usleep() by default; the kernel exports it. */
extern int usleep(unsigned int useconds);

/* ST7789 command bytes (spec, Sitronix ST7789V data sheet rev 1.10) */
#define ST7789_SWRESET  0x01
#define ST7789_SLPOUT   0x11
#define ST7789_NORON    0x13
#define ST7789_INVON    0x21
#define ST7789_DISPON   0x29
#define ST7789_CASET    0x2A
#define ST7789_RASET    0x2B
#define ST7789_RAMWR    0x2C
#define ST7789_MADCTL   0x36
#define ST7789_COLMOD   0x3A

struct disp_ctx_s {
    int      spi_fd;
    int      gpio_fd;
    /* device-specific state copied from <duneos/board.h> at open time */
    int      cs, dc, rst, bl;
    uint16_t width, height;
    uint8_t  swap_xy;
    uint16_t col_offset, row_offset;
};

/* ---- SPI / GPIO helpers ------------------------------------------------- */

static int open_spi_dev(disp_ctx_t *c)
{
#ifndef DUNEOS_DISPLAY_DEV_INDEX
    /* Board doesn't expose the display SPI as a raw bus — userspace path
     * isn't applicable here. Fail explicitly so a misconfiguration shows. */
    errno = ENODEV;
    return -1;
#else
    char path[16];
    snprintf(path, sizeof(path), "/dev/spi-%d", DUNEOS_DISPLAY_DEV_INDEX);
    int fd = open(path, O_RDWR);
    if (fd < 0) return -1;

    uint8_t  mode = 0;                          ioctl(fd, SPI_SET_MODE,  &mode);
    uint32_t hz   = DUNEOS_DISPLAY_FREQ_HZ;     ioctl(fd, SPI_SET_SPEED, &hz);
    int      cs   = c->cs;                      ioctl(fd, SPI_SET_CS,    &cs);
    return fd;
#endif
}

static void gpio_set_out(int fd, int line, int val)
{
    gpio_req_t req = { .line = (uint8_t)line, .dir = 1 /* OUTPUT */, .val = (uint8_t)val };
    ioctl(fd, GPIOCHIP_SET_DIR,   &req);
    ioctl(fd, GPIOCHIP_SET_VALUE, &req);
}

static void gpio_write(int fd, int line, int val)
{
    gpio_req_t req = { .line = (uint8_t)line, .val = (uint8_t)val };
    ioctl(fd, GPIOCHIP_SET_VALUE, &req);
}

/* ---- SPI command / data primitives -------------------------------------- */

static void st_cmd(disp_ctx_t *c, uint8_t cmd)
{
    gpio_write(c->gpio_fd, c->dc, 0);   /* DC low = command */
    write(c->spi_fd, &cmd, 1);
}

static void st_data(disp_ctx_t *c, const void *data, size_t len)
{
    if (!len) return;
    gpio_write(c->gpio_fd, c->dc, 1);   /* DC high = data */
    /* Chunk large transfers — many kernel SPI drivers cap per-ioctl size. */
    const uint8_t *p = data;
    while (len) {
        size_t chunk = len > 2048 ? 2048 : len;
        write(c->spi_fd, p, chunk);
        p   += chunk;
        len -= chunk;
    }
}

static void st_set_window(disp_ctx_t *c, uint16_t x, uint16_t y, uint16_t w, uint16_t h)
{
    uint16_t cs, ce, rs, re;
    if (c->swap_xy) {
        cs = x + c->row_offset; ce = cs + w - 1;
        rs = y + c->col_offset; re = rs + h - 1;
    } else {
        cs = x + c->col_offset; ce = cs + w - 1;
        rs = y + c->row_offset; re = rs + h - 1;
    }
    uint8_t buf[4];

    buf[0] = cs >> 8; buf[1] = cs & 0xFF;
    buf[2] = ce >> 8; buf[3] = ce & 0xFF;
    st_cmd(c, ST7789_CASET);
    st_data(c, buf, 4);

    buf[0] = rs >> 8; buf[1] = rs & 0xFF;
    buf[2] = re >> 8; buf[3] = re & 0xFF;
    st_cmd(c, ST7789_RASET);
    st_data(c, buf, 4);

    st_cmd(c, ST7789_RAMWR);
}

/* ---- backend ops (disp_backend_ops_t) ---------------------------------- */

static disp_ctx_t *st7789_backend_open(void)
{
#ifndef DUNEOS_DISPLAY_DEV_INDEX
    /* Board's display SPI isn't on a raw bus — caller (libgfx) should be
     * using /dev/fb0 (Tier B) instead. Refuse cleanly. */
    return NULL;
#else
    disp_ctx_t *c = calloc(1, sizeof(*c));
    if (!c) return NULL;
    c->spi_fd  = -1;
    c->gpio_fd = -1;

    c->width      = DUNEOS_DISPLAY_WIDTH;
    c->height     = DUNEOS_DISPLAY_HEIGHT;
    c->cs         = DUNEOS_DISPLAY_CS_PIN;
    c->dc         = DUNEOS_DISPLAY_DC_PIN;
    c->rst        = DUNEOS_DISPLAY_RST_PIN;
    c->bl         = DUNEOS_DISPLAY_BL_PIN;
    c->swap_xy    = DUNEOS_DISPLAY_SWAP_XY;
    c->col_offset = DUNEOS_DISPLAY_COL_OFFSET;
    c->row_offset = DUNEOS_DISPLAY_ROW_OFFSET;

    /* SPI bus: open + configure (mode, speed, CS). */
    c->spi_fd = open_spi_dev(c);
    if (c->spi_fd < 0) { free(c); return NULL; }

    /* GPIO bank 0 for DC (mandatory) + RST/BL (optional). */
    c->gpio_fd = open("/dev/gpiochip0", O_RDWR);
    if (c->gpio_fd < 0) { close(c->spi_fd); free(c); return NULL; }
    gpio_set_out(c->gpio_fd, c->dc, 1);
    if (c->rst >= 0) gpio_set_out(c->gpio_fd, c->rst, 1);
    if (c->bl  >= 0) gpio_set_out(c->gpio_fd, c->bl,  0);   /* off until init OK */

    /* Hardware reset: pull RST low ~10 ms, release, wait ~120 ms. */
    if (c->rst >= 0) {
        gpio_write(c->gpio_fd, c->rst, 0);
        usleep(10 * 1000);
        gpio_write(c->gpio_fd, c->rst, 1);
        usleep(120 * 1000);
    }

    /* Init sequence — mirrors kernel st7789_hw.c with identical timings. */
    st_cmd(c, ST7789_SWRESET); usleep(120 * 1000);
    st_cmd(c, ST7789_SLPOUT);  usleep(120 * 1000);
    st_cmd(c, ST7789_COLMOD);  { uint8_t v = 0x55;                       st_data(c, &v, 1); }
    st_cmd(c, ST7789_MADCTL);  { uint8_t v = DUNEOS_DISPLAY_MADCTL;      st_data(c, &v, 1); }
    st_cmd(c, ST7789_INVON);
    st_cmd(c, ST7789_NORON);   usleep(10 * 1000);
    st_cmd(c, ST7789_DISPON);  usleep(10 * 1000);

    /* Clear panel to black so we don't ship random RAM contents. */
    {
        uint16_t row[320] = { 0 };
        if (c->width <= sizeof(row) / sizeof(row[0])) {
            st_set_window(c, 0, 0, c->width, c->height);
            for (uint16_t y = 0; y < c->height; y++) st_data(c, row, (size_t)c->width * 2);
        }
    }

    /* Backlight on. */
    if (c->bl >= 0) gpio_write(c->gpio_fd, c->bl, 1);

    return c;
#endif
}

static uint16_t st7789_backend_width(const disp_ctx_t *c)  { return c ? c->width  : 0; }
static uint16_t st7789_backend_height(const disp_ctx_t *c) { return c ? c->height : 0; }

/* ST7789 expects big-endian RGB565 on the wire. We byte-swap into a small
 * line buffer; callers can pass native-endian uint16_t. */
static void st7789_backend_write_area(disp_ctx_t *c,
                                       uint16_t x, uint16_t y,
                                       uint16_t w, uint16_t h,
                                       const uint16_t *pixels)
{
    if (!c || !pixels || !w || !h) return;
    st_set_window(c, x, y, w, h);

    uint16_t line[320];           /* widest ST7789 variant */
    if (w > sizeof(line) / sizeof(line[0])) return;
    for (uint16_t row = 0; row < h; row++) {
        for (uint16_t col = 0; col < w; col++) {
            uint16_t p = pixels[row * w + col];
            line[col] = (uint16_t)((p << 8) | (p >> 8));
        }
        st_data(c, line, (size_t)w * 2);
    }
}

static void st7789_backend_close(disp_ctx_t *c)
{
    if (!c) return;
    /* Do NOT turn the backlight off on close. The display is a shared
     * resource — another app (e.g. g_shell running concurrently) may
     * still be using it. The BL pin is board-level, not per-fd.
     * Apps that want a power-off path should write the BL pin directly
     * via /dev/gpiochip0. */
    if (c->spi_fd  >= 0) close(c->spi_fd);
    if (c->gpio_fd >= 0) close(c->gpio_fd);
    free(c);
}

/* duneos_disp_ops — the symbol libdisp.c dispatches through. Single chip
 * per .dap (multiple libchip*.c linked together would collide on this
 * symbol — enforced by the linker, which is what we want). */
const disp_backend_ops_t duneos_disp_ops = {
    .open       = st7789_backend_open,
    .width      = st7789_backend_width,
    .height     = st7789_backend_height,
    .write_area = st7789_backend_write_area,
    .close      = st7789_backend_close,
};
