#pragma once

/*
 * Board configuration for ESP32-S3-DevKitC-1.
 *
 * THIS FILE IS MANUALLY WRITTEN FOR NOW.
 * In Phase 4 it will be generated by: duneos-bspgen esp32s3-devkitc.yaml
 *
 * Do not edit by hand once duneos-bspgen is in place.
 */

#define DUNEOS_BOARD_NAME       "esp32s3-devkitc"
#define DUNEOS_CPU_ESP32S3      1
#define DUNEOS_FLASH_SIZE_MB    8
#define DUNEOS_PSRAM_SIZE_MB    8

/* ---------- UART0 (console) ---------- */
#define DUNEOS_UART0_TX_PIN     43
#define DUNEOS_UART0_RX_PIN     44
#define DUNEOS_UART0_BAUD       115200

/* ---------- SPI2 (SD card) ---------- */
#define DUNEOS_SD_SPI_HOST      SPI2_HOST
#define DUNEOS_SD_MOSI_PIN      11
#define DUNEOS_SD_MISO_PIN      13
#define DUNEOS_SD_CLK_PIN       12
#define DUNEOS_SD_CS_PIN        10
#define DUNEOS_SD_FREQ_KHZ      20000   /* 20 MHz — safe default, raise if stable */
#define DUNEOS_SD_CD_PIN        (-1)    /* card detect not wired */

/* ---------- Status LED ---------- */
#define DUNEOS_LED_STATUS_PIN   2
#define DUNEOS_LED_ACTIVE_HIGH  1
