#!/usr/bin/env python3
"""
duneos-bspgen — DuneOS Board Support Package Generator
=======================================================
Reads a board YAML descriptor and generates the board_config.h header that
DuneOS kernel components include to learn pin assignments and hardware options.

Usage:
    python duneos-bspgen.py boards/m5stack-cardputer.yaml
    python duneos-bspgen.py boards/esp32s3-devkitc.yaml --out boards/esp32s3-devkitc/board_config.h

The output path defaults to  boards/<board_name>/board_config.h  next to the YAML.

YAML schema (all keys under the top-level 'board:' key):
  name          string   Board identifier (directory name, no spaces)
  cpu           string   esp32s3 | esp32 | esp32s2 | esp32c3
  flash_size_mb int
  psram_size_mb int      0 if no PSRAM
  psram_type    string   opi | qspi   (ignored if psram_size_mb == 0)
  uart:
    - id: N
      tx_pin: N
      rx_pin: N
      default_baud: N
  spi:
    - id: N             SPI host number (2=SPI2_HOST, 3=SPI3_HOST)
      mosi_pin: N
      miso_pin: N
      clk_pin: N
      cs_pin: N        (per-device CS; for SD the cs comes from sd_card section)
      max_freq_hz: N
  sd_card:
      interface: spi
      spi_id: N        references spi[].id
      cd_pin: N        -1 if not present
  i2c:
    - id: N
      sda_pin: N
      scl_pin: N
      freq_hz: N
  display:
      driver: st7789 | ili9341 | ...
      width: N
      height: N
      spi_host: SPI2_HOST | SPI3_HOST
      mosi_pin: N
      clk_pin: N
      cs_pin: N
      dc_pin: N
      rst_pin: N
      bl_pin: N
      freq_hz: N
  keyboard:
      i2c_id: N
      i2c_addr: 0xNN
  leds:
    - id: status | ...
      pin: N
      active_high: true|false
      type: gpio | ws2812    (optional, default gpio)

Requirements:
    pip install pyyaml
"""

import argparse
import sys
from pathlib import Path
from datetime import datetime, timezone

try:
    import yaml
except ImportError:
    sys.exit(
        "ERROR: pyyaml not installed.\n"
        "Install it with:  pip install pyyaml\n"
        "Or in the ESP-IDF Python env:  python -m pip install pyyaml"
    )

# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

REQUIRED_BOARD_KEYS = ["name", "cpu"]
VALID_CPUS = {"esp32", "esp32s2", "esp32s3",
              "esp32c2", "esp32c3", "esp32c5", "esp32c6",
              "esp32h2", "esp32p4"}

# Architecture classification (same sets used by dbt.py)
XTENSA_CPUS = {"esp32", "esp32s2", "esp32s3"}
RISCV_CPUS  = VALID_CPUS - XTENSA_CPUS


def die(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def validate(board: dict, yaml_path: Path) -> None:
    for k in REQUIRED_BOARD_KEYS:
        if k not in board:
            die(f"'{yaml_path}' is missing required field: board.{k}")
    if board["cpu"] not in VALID_CPUS:
        die(f"Unknown cpu '{board['cpu']}'. Valid: {', '.join(sorted(VALID_CPUS))}")

    if "sd_card" in board:
        sd = board["sd_card"]
        spi_id = sd.get("spi_id")
        if spi_id is not None:
            spi_ids = [s.get("id") for s in board.get("spi", [])]
            if spi_id not in spi_ids:
                die(f"sd_card.spi_id={spi_id} references a SPI bus not defined in spi[]")


# ---------------------------------------------------------------------------
# Header generation
# ---------------------------------------------------------------------------

SPI_HOST_NAMES = {2: "SPI2_HOST", 3: "SPI3_HOST", 1: "SPI1_HOST"}


def _define(name: str, value) -> str:
    if isinstance(value, bool):
        return f"#define {name:<40} {1 if value else 0}"
    if isinstance(value, str):
        return f'#define {name:<40} {value}'
    return f"#define {name:<40} {value}"


def generate(board: dict) -> str:
    lines = []
    name = board["name"]
    cpu  = board["cpu"]

    lines += [
        "#pragma once",
        "",
        f"/*",
        f" * board_config.h for {name}",
        f" * Generated by duneos-bspgen on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f" * DO NOT EDIT — re-generate from boards/{name}.yaml",
        f" */",
        "",
    ]

    # ----- identity -----
    arch       = "xtensa" if cpu in XTENSA_CPUS else "riscv"
    em_machine = "EM_XTENSA" if arch == "xtensa" else "EM_RISCV"

    lines += [
        _define("DUNEOS_BOARD_NAME",         f'"{name}"'),
        _define(f"DUNEOS_CPU_{cpu.upper()}", 1),
        _define("DUNEOS_CPU_ARCH",           f'"{arch}"'),
        _define("DUNEOS_ELF_MACHINE",        em_machine),
        _define("DUNEOS_FLASH_SIZE_MB",      board.get("flash_size_mb", 4)),
        _define("DUNEOS_PSRAM_SIZE_MB",      board.get("psram_size_mb", 0)),
        "",
    ]

    # ----- UART -----
    uarts = board.get("uart", [])
    for u in uarts:
        uid = u["id"]
        pfx = f"DUNEOS_UART{uid}"
        lines += [
            f"/* ---------- UART{uid} ---------- */",
            _define(f"{pfx}_TX_PIN",  u["tx_pin"]),
            _define(f"{pfx}_RX_PIN",  u["rx_pin"]),
            _define(f"{pfx}_BAUD",    u.get("default_baud", 115200)),
            "",
        ]

    # ----- SD card -----
    sd = board.get("sd_card")
    if sd:
        spi_id  = sd.get("spi_id")
        cd_pin  = sd.get("cd_pin", -1)
        spi_bus = next((s for s in board.get("spi", []) if s.get("id") == spi_id), None)
        if spi_bus:
            host_name = SPI_HOST_NAMES.get(spi_id, f"SPI{spi_id}_HOST")
            freq_khz  = spi_bus.get("max_freq_hz", 20_000_000) // 1000
            lines += [
                "/* ---------- SPI SD card ---------- */",
                _define("DUNEOS_SD_SPI_HOST",  host_name),
                _define("DUNEOS_SD_MOSI_PIN",  spi_bus["mosi_pin"]),
                _define("DUNEOS_SD_MISO_PIN",  spi_bus["miso_pin"]),
                _define("DUNEOS_SD_CLK_PIN",   spi_bus["clk_pin"]),
                _define("DUNEOS_SD_CS_PIN",    spi_bus["cs_pin"]),
                _define("DUNEOS_SD_FREQ_KHZ",  freq_khz),
                _define("DUNEOS_SD_CD_PIN",    cd_pin),
                "",
            ]

    # ----- I2C -----
    for i2c in board.get("i2c", []):
        iid = i2c["id"]
        pfx = f"DUNEOS_I2C{iid}"
        lines += [
            f"/* ---------- I2C{iid} ---------- */",
            _define(f"{pfx}_SDA_PIN",  i2c["sda_pin"]),
            _define(f"{pfx}_SCL_PIN",  i2c["scl_pin"]),
            _define(f"{pfx}_FREQ_HZ",  i2c.get("freq_hz", 400_000)),
            "",
        ]

    # ----- Display -----
    disp = board.get("display")
    if disp:
        host_name = disp.get("spi_host", "SPI3_HOST")
        lines += [
            "/* ---------- Display ---------- */",
            _define("DUNEOS_DISPLAY_WIDTH",    disp["width"]),
            _define("DUNEOS_DISPLAY_HEIGHT",   disp["height"]),
            _define("DUNEOS_DISPLAY_SPI_HOST", host_name),
            _define("DUNEOS_DISPLAY_MOSI_PIN", disp["mosi_pin"]),
            _define("DUNEOS_DISPLAY_CLK_PIN",  disp["clk_pin"]),
            _define("DUNEOS_DISPLAY_CS_PIN",   disp["cs_pin"]),
            _define("DUNEOS_DISPLAY_DC_PIN",   disp["dc_pin"]),
            _define("DUNEOS_DISPLAY_RST_PIN",  disp["rst_pin"]),
            _define("DUNEOS_DISPLAY_BL_PIN",   disp.get("bl_pin", -1)),
            _define("DUNEOS_DISPLAY_FREQ_HZ",  disp.get("freq_hz", 20_000_000)),
            "",
        ]

    # ----- Keyboard -----
    kb = board.get("keyboard")
    if kb:
        lines += [
            "/* ---------- Keyboard ---------- */",
            _define("DUNEOS_KB_I2C_ADDR", hex(kb["i2c_addr"]) if isinstance(kb["i2c_addr"], int) else kb["i2c_addr"]),
            "",
        ]

    # ----- LEDs -----
    for led in board.get("leds", []):
        lid = led["id"].upper()
        lines += [
            f"/* ---------- LED {led['id']} ---------- */",
            _define(f"DUNEOS_LED_{lid}_PIN",         led["pin"]),
            _define(f"DUNEOS_LED_{lid}_ACTIVE_HIGH",  1 if led.get("active_high", True) else 0),
        ]
        if led.get("type") == "ws2812":
            lines.append(_define(f"DUNEOS_LED_{lid}_WS2812", 1))
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="duneos-bspgen",
        description="Generate board_config.h from a DuneOS board YAML descriptor",
    )
    parser.add_argument("yaml", help="Path to board YAML file")
    parser.add_argument("--out", help="Output path (default: boards/<name>/board_config.h)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print generated header to stdout, do not write file")
    args = parser.parse_args()

    yaml_path = Path(args.yaml)
    if not yaml_path.exists():
        die(f"File not found: {yaml_path}")

    with open(yaml_path) as f:
        doc = yaml.safe_load(f)

    if "board" not in doc:
        die(f"'{yaml_path}' has no top-level 'board:' key")

    board = doc["board"]
    validate(board, yaml_path)

    header = generate(board)

    if args.dry_run:
        print(header)
        return

    name = board["name"]
    if args.out:
        out_path = Path(args.out)
    else:
        out_path = yaml_path.parent / name / "board_config.h"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header + "\n")
    print(f"Generated: {out_path}")


if __name__ == "__main__":
    main()
